# Generated by Django 4.0.2 on 2022-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_payment_eventregistration_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='booking_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='booking_start',
            field=models.DateField(),
        ),
    ]
