# Generated by Django 4.0.2 on 2022-02-24 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_events_booking_end_alter_events_booking_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='scheduled_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 21, 23, 4, 430644, tzinfo=utc)),
        ),
    ]
