# Generated by Django 4.0.2 on 2022-02-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_events_scheduled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='scheduled_on',
            field=models.DateTimeField(),
        ),
    ]
