# Generated by Django 4.0.2 on 2022-02-24 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_events_scheduled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='booking_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 21, 38, 51, 657822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='booking_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 21, 38, 51, 657807, tzinfo=utc)),
        ),
    ]
