# Generated by Django 4.0.2 on 2022-02-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_events_booking_end_alter_events_booking_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='booking_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='booking_start',
            field=models.DateTimeField(),
        ),
    ]
